### ISSUE TITLE
Symbol "SYSTEM-VERSION" not found in the ASDF/INTERFACE package. [ASDF=3.3.1]

### ISSUE THREAD

**Issue by omarbassam88** [40ants/40ants-asdf-system#5]
Trying to load `(ql:quickload :40ants-asdf-system :verbose t :explain t)`

I get this error when it is trying to compile the file src/system.lisp:
```
; compiling file "/home/omar/quicklisp/dists/ultralisp/software/40ants-40ants-asdf-system-20221110175211/src/system.lisp" (written 10 FEB 2023 04:10:08 PM):
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "SYSTEM-VERSION" not found in the ASDF/INTERFACE package.
;   
;       Line: 30, Column: 34, File-Position: 1391
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/omar/quicklisp/dists/ultralisp/software/40ants-40ants-asdf-system-20221110175211/src/system.lisp" {10030630D3}>

```

When I try to run the `asdf:system-version` function I get an error that this symbol is not found in ASDF/INTERFACE package.

**Comment by svetlyak40wt** [comment]
Please, provide an output of `(asdf:asdf-version)`.

**Comment by omarbassam88** [comment]
asdf:asdf-version  => "3.3.1"
sbcl => 2.2.9

**Comment by svetlyak40wt** [comment]
[Blame](https://github.com/fare/asdf/blame/11a691c03eba55b718a154b673a7b77eb63eb244/interface.lisp) says that system-version was added in 3.3.2.11.

I need to investigate if it possible to support ASDF <  3.3.2.11.

**Comment by svetlyak40wt** [comment]
Should be fixed in https://github.com/40ants/40ants-asdf-system/pull/6 PR.

**Comment by omarbassam88** [comment]
Yes It works now.
Thank You
